### ISSUE TITLE
Printer stays on X-axis endpoint once print is finsihed

### ISSUE THREAD

**Issue by ghost** [Desuuuu/DGUS-reloaded-config#3]
Printer: Creality CR10s-Pro V2

Issue:
After the printer has finished the part the X-Axis moves to the endpoint, disables the stepper motors and stays there.
It would be good if the printer just moves to X 0 and disables the stepper motors, as it is not good to stay on the end switches.

**Comment by Desuuuu** [comment]
IIRC, the only command ran by the firmware after a print from the SD card is `M84 X Y E` (as configured [here](https://github.com/Desuuuu/DGUS-reloaded-config/blob/2.0.x/examples/Creality/CR10SProV2/Configuration_adv.h#L1124)).

Anything else getting executed after a print is most likely the end G-code added by your slicer.

In any case, the best way to customize the post-print behaviour of your printer is to edit your slicer's settings (the end G-code option).

**Comment by ghost** [comment]
Thank you! You were right cura is adding this line:
```
G1 X0 Y{machine_depth} ;Present print
```
I set it to ```G1 X20 Y{machine_depth}``` now it is ok

Something must be different in the measurement of the x-axis, though. I have not changed this g-code and with the stock firmware the printer did not move to the x endpoint with ```G1 X0```.

Anyway, it works now so thanks for your help!
