### ISSUE TITLE
BLtouch do not compensate mesh variations.... tmc2208s problems?

### ISSUE THREAD

**Issue by OMG809** [Desuuuu/DGUS-reloaded-config#5]
Hi Desuuu. I'm coming from klipper and using the base of you config file for my cr10spro v2 whith genuine bltouch.
I try many different options but bltouch do not compensate the mesh variation during printing.
I dont know why but this problem is common to many users with cr10spro and other printers with tmc2208s.

I wanted to find out if you have encountered this problem. Bltouch was born for leveling on slightly deformed beds, but with klipper this doesn't seem to work.

What do you suggest?
I was thinking of using your fork of klipper and dwin before returning to Marlin (I believe I will adopt your repo), but before that I wanted to make sure there is no way to really solve the problem between klipper and tmc2208s.

I hope in your reply
[last-Klippy_Log_and_printer-CFG.zip](https://github.com/Desuuuu/DGUS-reloaded-config/files/6411477/last-Klippy_Log_and_printer-CFG.zip)

**Comment by Desuuuu** [comment]
Please direct your issues upstream for things that are not specifically related to this fork.

I don't see any reason this wouldn't work and I don't think this is common at all.

**Comment by OMG809** [comment]
I am writing here because I have already written all the problems encountered on klipper I was wondering, since you wrote this fork, if I had this kind of problem.
